### ISSUE TITLE
Cannot use connection string url to connect

### ISSUE THREAD

**Issue by nrempel** [adonisjs/adonis-redis#12]
Hello,

For some reason, if I use a connection string to connect it attempts to connect to `127.0.0.1:6379`:

config:
```
..
docker: 'redis://redis:6379',
..
```

error:
```
server_1    | [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
server_1    |     at Object._errnoException (util.js:999:13)
server_1    |     at _exceptionWithHostPort (util.js:1020:20)
```

In order for the provider to connect correctly I need to use:

config:

```
...
  docker: {
    host: 'redis',
    port: 6379,
    password: null,
    db: 0,
    keyPrefix: ''
  },
...
```

But `ioredis` does allow connecting via connection string:

https://github.com/luin/ioredis#connect-to-redis

**Comment by thetutlage** [comment]
I tried using it with `redis://localhost:6379` which works fine. Also it passes the exact string to IoRedis, so it should work fine.

Are you are sure that DB is accessible on `redis://redis:6379`

<img width="655" alt="screen shot 2018-01-06 at 4 47 33 pm" src="https://user-images.githubusercontent.com/1706381/34639219-62ca1904-f301-11e7-8310-849a4916425b.png">

**Comment by nrempel** [comment]
hmm that's weird.

Redis is definitely available at that address because the second method works to connect.

I'll try to create an example repo to show the issue soon.

**Comment by thetutlage** [comment]
Sure lemme also try it with Docker, that what you are using right?

**Comment by nrempel** [comment]
Yeah, docker-compose.

My environment is doing a bit more, but this should reproduce my Redis environment.

`docker-compose.yml`
```
version: '3'
services:
  server:
    build: .
    command: 'bash -c ''adonis serve --dev --debug'''
    environment:
      PORT: 9000
      REDIS_URL: 'redis://redis:6379'
    ports:
      - '9000:9000'
      - '9229:9229'
    links:
      - postgres
      - redis

  redis:
    image: redis
```

`Dockerfile`
```
FROM node

RUN npm i -g @adonisjs/cli

ADD ./app /app
WORKDIR /app

RUN npm i
```
